version = 5.2.2
archive_dir = /etc/letsencrypt/archive/gif-server.duckdns.org
cert = /etc/letsencrypt/live/gif-server.duckdns.org/cert.pem
privkey = /etc/letsencrypt/live/gif-server.duckdns.org/privkey.pem
chain = /etc/letsencrypt/live/gif-server.duckdns.org/chain.pem
fullchain = /etc/letsencrypt/live/gif-server.duckdns.org/fullchain.pem
[renewalparams]
account = cbe5c454370581093202855e978562e6
pref_challs = dns-01,
authenticator = dns-duckdns
dns_duckdns_propagation_seconds = 60
dns_duckdns_token = 1c556df1-9970-424e-a7e3-0c06c1443aef
server = https://acme-v02.api.letsencrypt.org/directory
key_type = ecdsa
[acme_renewal_info]
ari_retry_after = 2026-04-15T18:10:21
