name: Spring Boot CD
on:
  push:
    branches: ['main']
jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: 서버 배포
        run: |
          set -e
          cd ~/GIF_SERVER
          git fetch origin main
          git checkout main
          git reset --hard origin/main
          docker compose up -d --build
          docker image prune -f

      - name: Discord 알림 (성공)
        if: ${{ success() }}
        continue-on-error: true
        uses: sarisia/actions-status-discord@v1
        with:
          webhook: ${{ secrets.DISCORD_GIF_SERVER }}
          ack_no_webhook: true
          title: '✅ 성공 했다능! ✅'
          status: ${{ job.status }}
          description: '서버 배포 성공'
          color: 65280
          username: 'GIF-SERVER-bot'

      - name: Discord 알림 (실패)
        if: ${{ failure() }}
        continue-on-error: true
        uses: sarisia/actions-status-discord@v1
        with:
          webhook: ${{ secrets.DISCORD_GIF_SERVER }}
          ack_no_webhook: true
          title: '❗️ 실패했다능! ❗️'
          status: ${{ job.status }}
          description: '서버 배포 실패'
          color: 16711680
          username: 'GIF-SERVER-bot'
